### ISSUE TITLE
new 2.2.x release?

### ISSUE THREAD

**Issue by agitator** [plone/Products.CMFCore#4]
since pr's connected to https://github.com/zopefoundation/Products.CMFCore/pull/12 have been merged within CMFPlone?

**Comment by icemac** [comment]
@agitator According to the [change log on the 2.2 branch of the ZF repos](https://github.com/zopefoundation/Products.CMFCore/blob/2.2/Products/CMFCore/CHANGES.txt) there are no unreleased changes. Which commits do you want to get released?

**Comment by agitator** [comment]
i didn't realize that the fork was merged back to zf repos

**Comment by tomgross** [comment]
If the fork got merged back this should be deleted to avoid further confusion.
